version: "3.8"
services:
  my_frontend:
    build: ./frontend
    container_name: "my_frontend"
    ports:
      - '8000:8000'
    volumes:
      - ./frontend:/var/www/html/app
      - "/var/www/html/app/node_modules"

